det = turtle.detect()

function antiGravel()
    det = turtle.detect()
    while det do
        turtle.dig()
        sleep(0.2)
        det = turtle.detect()
    end
end

for i=1,20 do
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.turnRight()
    turtle.digUp()
    turtle.digDown()
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.digUp()
    turtle.digDown()
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.turnLeft()
    turtle.digUp()
    turtle.digDown()
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.turnLeft()
    turtle.digUp()
    turtle.digDown()
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.digUp()
    turtle.digDown()
    turtle.dig()
    antiGravel()
    turtle.forward()
    turtle.turnRight()
    turtle.digUp()
    turtle.digDown()
end
